/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.wordcloud;


import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.io.IOException;

public class MainWindow extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

/**
 * The main entry point for all JavaFX applications.
 * The start method is called after the init method has returned,
 * and after the system is ready for the application to begin running.
 *
 * <p>
 * NOTE: This method is called on the JavaFX Application Thread.
 * </p>
 *
 * @param primaryStage the primary stage for this application, onto which
 *                     the application scene can be set.
 *                     Applications may create other stages, if needed, but they will not be
 *                     primary stages.
 * @throws Exception if something goes wrong
 */
@Override
public void start(Stage primaryStage) throws Exception {
    openMainWindow(primaryStage);
}
private void openMainWindow(Stage stage) throws IOException {
    FXMLLoader loader =new FXMLLoader(getClass().getResource(" MainWindow.fxml "));
    
    Pane rootNode = loader.load();
    
    Scene scene = new Scene(rootNode);
    stage.setScene(scene);
    
    MainWindowController controller = loader.getController();
    
    stage.show();
    
}
}
