/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.wordcloud;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainWindowTest {
    @Test void appHasAGreeting() {
        MainWindow classUnderTest = new MainWindow();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
